docs: 添加csv表头优化相关TODO
nan-mu/ldc1614-test pull request #15
Opened 2024-12-17 09:15 UTC by A-n-uo

进行csv格式优化

2025-01-02 06:49 UTC, nan-mu commented on 1.mmd
这是啥？没用的话删了

2025-01-02 06:53 UTC, nan-mu commented on src/handler.rs
> +}
嗯...最好起一个有含义的名字
```suggestion
// 定义 CsvRecordA 结构体
#[derive(Debug, Serialize)]
pub struct CsvRecordA {
    //pub timestamp: String,  // 时间戳
    pub mark: Option<String>, // 可选标记
    pub channel: u8,          // 通道
    pub data: u32,            // 数据
}

// 定义 CsvRecordB 结构体
#[derive(Debug, Serialize)]
pub struct CsvRecordB {
    // pub timestamp: String,  // 时间戳
    pub mark: Option<String>, // 可选标记
    pub channel: u8,          // 通道
    pub data: u32,            // 数据
    pub settlecount: u16,     // settlecount 寄存器值
    pub rcount: u16,          // rcount 寄存器值
}
```

2025-01-03 06:57 UTC, nan-mu commented
@A-n-uo @live3w

2025-01-05 03:25 UTC, live3w commented on src/handler.rs
> +}
> 嗯...最好起一个有含义的名字

嘶，这个名字就是定义的两种结构体ab的名字，没想好咋改

2025-01-05 03:27 UTC, live3w commented on 1.mmd
已经删除了

2025-01-09 17:08 UTC, nan-mu requested changes
可见性测试1

2025-01-09 17:09 UTC, nan-mu approved these changes
可见性测试2

2025-01-09 17:09 UTC, nan-mu reviewed
可见性测试3

2025-01-09 17:49 UTC, nan-mu requested changes
可见性测试8

2025-01-09 17:49 UTC, nan-mu commented on src/config.rs
可见性测试4

这样，我们将RecordType从handler::a移到这里，并且改名为CsvRecordType。我认为这样语义更清晰一些，CsvRecordType只会包含表意的枚举类型，而在handler::a很明显以及有具体的csv表头结构题代表这些类型了。

再者，handler::a中只有代码使用，而config这里作为类型使用。类型声明和它的子类型应该靠近。

2025-01-09 17:49 UTC, nan-mu commented on src/handler.rs
> +}
可见性测试5
像之前说的，三个需求对应三个结构体。但现在看来这部分想在新的代码里面复用的话，我们可能就只需要两个结构体，分别是最简单的和最复杂的。前者只有position和data，后者除了这两者还要有channel，time，settlecount，rount，mark。

这部分脱了好久了，请尽快解决，起名困难就问ai，需求发给他。

2025-01-09 17:49 UTC, nan-mu commented on src/handler.rs
> +                                    }
可见性测试6

算是一个新任务，我建议你们新开一个分支。我需要删除所有和redis相关的代码，以防止像这样计划外的工作量。

新任务你们自己安排下人手，就从csv-perf差分再合并到csv-perf吧。和之前的任务一样，给我一个你们做好需要我做第一次审查的时间点。我很希望你们在这周末完成csv-perf和这个新任务

2025-01-09 17:49 UTC, nan-mu commented on src/main.rs
可见性测试7

我很好奇你们为什么没对main函数中的submit进行修改或者提出问题，在我看来这里缺少了两个东西：
1. 从yaml中读取配置，了解到你们应该使用何种csv文件格式
2. 对submit需要的参数做出隔离。现在的代码中通过直接传参让数据发往handler。但这种设计并不适合我们可变参数的场景。对于所有可能的参数，我们可以将一条csv记录需要的参数分为两类，一类是main函数提供的，一类是submit提供的。前者包括寄存器当前值，电机位置，mark（这个其实是预留参数，先不管，我本来的计划是从yaml里提供），数据来源通道。然后就是submit，其实只提供data和时间。对于这里的设计我希望你们先提提意见。但时间不要拖太长，这个任务已经拖太久了。

2025-02-18 05:31 UTC, nan-mu approved these changes
合！

2025-02-18 05:32 UTC, merged